[package]
name = "ric"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_cmd = "2.0.10"
clap = "4.1.11"
docker-api = "0.13.0"
tokio = { version = "1.26.0", features = ["full"] }
