name: Deploy

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose --release

    - name: Publish
      run: cargo publish
